# Jekyll Configuration File
# jeffwilcox.blog

base_url: https://jeffwilcox.blog
#base_url: /
destination: ../blog-site/

keep_files: ['wp-content', '.git', 'assets', '.github', 'bin']

description: "The blog of Jeff Wilcox: software engineer living in Seattle"
root_desc: "Jeff Wilcox is a Principal Software Engineer at Microsoft."

markdown: kramdown
#kramdown:
#    extensions:
#        - generate_toc
#pygments: false

highlighter: rouge

# Conforms to the same original WordPress format that I was using.
permalink:	/:year/:month/:title/

exclude: ['Rakefile', 'README.textile', 'server.bat']

include: ['.well-known', '.github', 'bin']

# Custom variables I use to define my primary and secondary CDN endpoints.
cdn: //az414997.vo.msecnd.net/waz/
